### ISSUE TITLE
Mutilple Action

### ISSUE THREAD

**Issue by Chans-exe** [abhinav/tmux-fastcopy#56]
Could we have a _plumb_ like feature

like, open this regex in my browser :

`set-option -g @fastcopy-regex-url  'some url regex'`

That would be so sweet to use this plugin 😆 
🥺 🙏🏻

**Comment by abhinav** [comment]
Hello, @Chans-exe!
That's a good idea. There are a few ways this could be supported that I'm trying to pick between:

1. Modifier actions: Instead of just pressing `a` or `b`, you will press `Shift+a` or `Shift+b` to execute `@fastcopy-shift-action`.
2. Per-regex actions: Selecting a value matched by `@fastcopy-regex-url` runs `@fastcopy-action-url` if set, otherwise `@fastcopy-action`.
3. Actions get access to the regex name via `$FASTCOPY_REGEX_NAME`.

I haven't picked one yet, but (3) feels like the most flexible option: it can do everything (2) can in exchange for slightly more setup from users.

**Comment by Chans-exe** [comment]
@abhinav 
It's great to hear that! 😄

I think (3) is good option either, but sometimes we just want to copy it instead open it, 
perhap (1) is only solution for this situation. 😦 

maybe trying to combine (1) and (3) for more flexible but functional action? 🤔
like: 
we can press `Prefix+Shift+F` (1) to trigger open action (3), or press `Prefix+f` just (copy it) trigger normal action!
then action still get access to the regex, and we still have choice to copy or not at the same time! 
😊 

I do hope my english ability won't mess you up 😂

**Comment by abhinav** [comment]
Yeah, some mix of (1) and (3) sounds like the way to go.
(1) gives you an alternative action, and (3) gives you control over that action on a per-regex basis.

**Comment by abhinav** [comment]
Finally got around to doing this.
@Chans-exe, (1) and (2) discussed above are now available in v0.9.0.

**Comment by Chans-exe** [comment]
@abhinav,
Sweet 🤗
